apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
configMapGenerator:
- name: varnish-default
  files:
  - varnish/default.vcl
- name: varnish-destination
  files:
  - varnish/destination.vcl
- name: varnish-verbose
  files:
  - varnish/verbose_builtin.vcl
- name: varnish-hit-miss
  files:
  - varnish/hit-miss.vcl
- name: haproxy
  files:
  - haproxy/haproxy.cfg
- name: client-side
  files:
  - static/index.html
  - static/style.css
  - static/app.js
- name: api-registration
  literals:
  - AUTHORIZATION_ENDPOINT=CHANGEME.api-server.example.com
  - TOKEN_ENDPOINT=CHANGEME.api-server.example.com
  - SCOPE=CHANGEME
  - REDIRECT_URI=CHANGEME.application-server.example.com/authorized
secretGenerator:
- name: api-registration
  literals:
  - CLIENT_ID=CHANGEME
  - CLIENT_SECRET=CHANGEME
- name: client-access-token
  literals:
  - ACCESS_TOKEN=Bearer
patches:
- target:
    kind: Deployment
    name: varnish
  path: set_registry.yaml
