apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
configMapGenerator:
- name: varnish-default
  files:
  - varbish/default.vcl
- name: varnish-destination
  files:
  - varnish/destination.vcl
- name: varnish-verbose
  files:
  - varnish/verbose_builtin.vcl
- name: varnish-hit-miss
  files:
  - varnish/hit-miss.vcl
- name: haproxy
  files:
  - haproxy/haproxy.cfg
- name: proxy-destination
  literals:
  - for-host=CHANGEME.proxy-host.example.com
- name: cors
  literals:
  - allow-origin=https://CHANGEME.api-client.example.com
- name: client-side
  files:
  - static/index.html
  - static/style.css
  - static/app.js
secretGenerator:
- name: client-authorization
  literals:
  - access-token=Bearer CHANGEME
patches:
- target:
    kind: Deployment
    name: varnish
  path: set_registry.yaml
