apiVersion: v1
kind: ServiceAccount
metadata:
  name: oauth-client
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: secret-renewer
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: secret-updater
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: renew-secrets
  namespace: default
subjects:
- kind: ServiceAccount
  name: oauth-client
  apiGroup: ""
roleRef:
  kind: Role
  name: secret-renewer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: update-secrets
  namespace: default
subjects:
- kind: ServiceAccount
  name: oauth-client
  apiGroup: ""
roleRef:
  kind: Role
  name: secret-updater
  apiGroup: rbac.authorization.k8s.io
